=== corona-warn-app/cwa-server/services/distribution/src/main/resources/dgc/dcc-validation-rule.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://webgate.acceptance.ec.europa.eu/dgcg-json-api/validation-rule.schema.json",
  "title": "EU DCC Validation Rule",
  "description": "Rule to validate an issued EU Digital Covid Certificate.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "AffectedFields",
    "Country",
    "CertificateType",
    "Description",
    "Engine",
    "EngineVersion",
    "Identifier",
    "Logic",
    "SchemaVersion",
    "Type",
    "ValidFrom",
    "ValidTo",
    "Version"
  ],
  "properties": {
    "Identifier": {
      "type": "string",
      "description": "The unique rule name",
      "pattern": "^(GR|VR|TR|RR|IR|BNR)-[A-Z]{2}-\\d{4}$"
    },
    "Type": {
      "type": "string",
      "description": "Type of the rule",
      "enum": [
        "Acceptance",
        "Invalidation",
        "BoosterNotification"
      ]
    },
    "Country": {
      "type": "string",
      "description": "ISO Country Code of rule owner",
      "pattern": "^[A-Z]{2}$"
    },
    "Region": {
      "type": "string",
      "description": "Additional Region property to precise country property.",
      "pattern": "^[A-Z0-9]{0,5}$"
    },
    "Version": {
      "type": "string",
      "description": "Version of the rule (Semver)",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "SchemaVersion": {
      "type": "string",
      "description": "Version of the used schema (Semver)",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "Engine": {
      "type": "string",
      "description": "Type of the RuleEngine"
    },
    "EngineVersion": {
      "type": "string",
      "description": "Version of the used engine (Semver)",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "CertificateType": {
      "type": "string",
      "description": "Type of the certificate",
      "enum": [
        "General",
        "Test",
        "Vaccination",
        "Recovery"
      ]
    },
    "Description": {
      "type": "array",
      "description": "Array of human readable description of the rule",
      "items": {
        "type": "object",
        "required": [
          "lang",
          "desc"
        ],
        "properties": {
          "lang": {
            "type": "string",
            "description": "Language of the description",
            "pattern": "^([a-z]{2}|[a-z]{2}-[a-z]{2})$"
          },
          "desc": {
            "type": "string",
            "description": "Description of this rule in specified language",
            "minLength": 20
          }
        }
      },
      "contains": {
        "type": "object",
        "required": [
          "lang",
          "desc"
        ],
        "properties": {
          "lang": {
            "type": "string",
            "description": "Language of the description",
            "pattern": "^en$"
          },
          "desc": {
            "type": "string",
            "description": "Human readable description of this rule in English language",
            "minLength": 20
          }
        }
      },
      "minItems": 1
    },
    "ValidFrom": {
      "type": "string",
      "description": "Start validity of the rule as ISO 8601 Timestamp (without ms, with timezone)",
      "format": "date-time",
      "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d([-+][0-2]\\d:[0-5]\\d|Z)$"
    },
    "ValidTo": {
      "type": "string",
      "description": "End validity of the rule as ISO 8601 Timestamp (without ms, with timezone)",
      "format": "date-time",
      "pattern": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d([-+][0-2]\\d:[0-5]\\d|Z)$"
    },
    "AffectedFields": {
      "type": "array",
      "description": "Fields of the payload which are used by the rule.",
      "items": {
        "type": "string",
        "description": "Affected field of payload"
      }
    },
    "Logic": {
      "type": "object",
      "description": "The logic payload in JSON",
      "minProperties": 1
    }
  }
}

=== corona-warn-app/cwa-server/services/distribution/src/main/resources/dgc/rule_3.json
{
  "Identifier": "RR-NL-0003",
  "Type": "Invalidation",
  "Country": "NL",
  "Version": "1.0.0",
  "SchemaVersion": "1.0.0",
  "Engine": "CERTLOGIC",
  "EngineVersion": "0.7.5",
  "CertificateType": "Recovery",
  "Description": [
    {
      "lang": "en",
      "desc": "The validity start date must be before the validity end date."
    }
  ],
  "ValidFrom": "2021-06-01T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",
  "AffectedFields": [
    "r.0",
    "r.0.df",
    "r.0.du"
  ],
  "Logic": {
    "if": [
      {
        "var": "payload.r.0"
      },
      {
        "before": [
          {
            "plusTime": [
              {
                "var": "payload.r.0.df"
              },
              0,
              "day"
            ]
          },
          {
            "plusTime": [
              {
                "var": "payload.r.0.du"
              },
              0,
              "day"
            ]
          }
        ]
      },
      true
    ]
  }
}

=== corona-warn-app/cwa-server/services/distribution/src/main/resources/dgc/bn_rule_1.json
{
  "Identifier": "BNR-DE-3298",
  "Type": "BoosterNotification",
  "Country": "DE",
  "Version": "1.0.0",
  "SchemaVersion": "1.0.0",
  "Engine": "CERTLOGIC",
  "EngineVersion": "1.0.0",
  "CertificateType": "General",
  "Description": [
    {
      "lang": "en",
      "desc": "Remember to get your second vaccine shot! Your first vaccination was more than 2 months ago."
    },
    {
      "desc": "Denken Sie an ihre zweite Impfung um ihre Grundimmunisierung abzuschlie√üen! Ihre Erstimpfung war vor mehr als 2 Monaten.",
      "lang": "de"
    }
  ],
  "ValidFrom": "2021-07-01T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",
  "AffectedFields": [

  ],
  "Logic": {
    "and": [
      {
        "===": [
          {
            "var": "payload.v.0.dn"
          },
          1
        ]
      },
      {
        "===": [
          {
            "var": "payload.v.0.sd"
          },
          2
        ]
      },
      {
        "before": [
          {
            "plusTime": [
              {
                "var": "payload.v.0.dt"
              },
              60,
              "day"
            ]
          },
          {
            "plusTime": [
              {
                "var": "external.validationClock"
              },
              0,
              "day"
            ]
          }
        ]
      },
      {
        "if": [
          {
            "var": "payload.r.0"
          },
          {
            "before": [
              {
                "plusTime": [
                  {
                    "var": "payload.r.0.df"
                  },
                  0,
                  "day"
                ]
              },
              {
                "plusTime": [
                  {
                    "var": "payload.v.0.dt"
                  },
                  0,
                  "day"
                ]
              }
            ]
          },
          true
        ]
      }
    ]
  }
}

=== corona-warn-app/cwa-server/services/distribution/src/test/resources/dgc/wiremock/rule.json
{"AffectedFields":["r.0","r.0.tg","t.0","t.0.tg","v.0","v.0.tg"],"CertificateType":"General","Country":"CH","Description":[{"desc":"The targeted disease agent must be COVID-19 of the value set list.","lang":"en"}],"Engine":"CertLogic","EngineVersion":"0.7.5","Identifier":"GR-CH-0001","Logic":{"and":[{"if":[{"var":"payload.r.0"},{"in":[{"var":"payload.r.0.tg"},["840539006"]]},true]},{"if":[{"var":"payload.t.0"},{"in":[{"var":"payload.t.0.tg"},["840539006"]]},true]},{"if":[{"var":"payload.v.0"},{"in":[{"var":"payload.v.0.tg"},["840539006"]]},true]}]},"SchemaVersion":"1.0.0","Type":"Acceptance","ValidFrom":"2021-09-22T12:00:00Z","ValidTo":"2031-01-01T00:00:00Z","Version":"1.0.1"}

=== corona-warn-app/cwa-server/services/distribution/src/main/resources/dgc/rule_2.json
{
  "Identifier": "TR-DE-0003",
  "Type": "Acceptance",
  "Country": "DE",
  "Version": "1.0.0",
  "SchemaVersion": "1.0.0",
  "Engine": "CERTLOGIC",
  "EngineVersion": "0.7.5",
  "CertificateType": "Test",
  "Description": [
    {
      "lang": "en",
      "desc": "The sample for an NAA test (e.g., PCR) must have been taken no longer than 72 hours ago."
    },
    {
      "lang": "de",
      "desc": "Die Probenahme für einen NAA-Test (z.B. PCR) darf maximal 72 Stunden zurückliegen."
    },
    {
      "lang": "fr",
      "desc": "Le prélèvement pour un test TAN (p. ex. PCR) ne doit pas dater de plus de 72 heures."
    },
    {
      "lang": "es",
      "desc": "Deben haber transcurrido 72 horas como máximo desde la extracción para una prueba de amplificación de ácidos nucleicos (por ejemplo, una PCR)."
    },
    {
      "lang": "it",
      "desc": "Il campione per il NAAT (test PRC) deve essere stato rilevato nelle ultime 72 ore."
    }
  ],
  "ValidFrom": "2021-07-01T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",
  "AffectedFields": [
    "t.0",
    "t.0.sc",
    "t.0.tt"
  ],
  "Logic": {
    "if": [
      {
        "var": "payload.t.0"
      },
      {
        "if": [
          {
            "===": [
              {
                "var": "payload.t.0.tt"
              },
              "LP6464-4"
            ]
          },
          {
            "not-after": [
              {
                "plusTime": [
                  {
                    "var": "external.validationClock"
                  },
                  0,
                  "day"
                ]
              },
              {
                "plusTime": [
                  {
                    "var": "payload.t.0.sc"
                  },
                  72,
                  "hour"
                ]
              }
            ]
          },
          true
        ]
      },
      true
    ]
  }
}

=== corona-warn-app/cwa-server/services/distribution/src/main/resources/dgc/rule_1.json
{
  "Identifier": "RR-NL-0000",
  "Type": "Acceptance",
  "Country": "NL",
  "Version": "1.0.0",
  "SchemaVersion": "1.0.0",
  "Engine": "CERTLOGIC",
  "EngineVersion": "0.7.5",
  "CertificateType": "Recovery",
  "Description": [
    {
      "lang": "en",
      "desc": "At most one r-event."
    }
  ],
  "ValidFrom": "2021-06-01T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",
  "AffectedFields": [
    "r.1"
  ],
  "Logic": {
    "!": [
      {
        "var": "payload.r.1"
      }
    ]
  }
}

=== corona-warn-app/cwa-server/services/distribution/src/test/resources/dgc/signature-verification/rule-by-country-and-hash.json
{
  "Identifier": "RR-DE-0001",
  "Type": "Acceptance",
  "Country": "DE",
  "Version": "1.0.0",
  "SchemaVersion": "1.0.0",
  "Engine": "CERTLOGIC",
  "EngineVersion": "0.7.5",
  "CertificateType": "Recovery",
  "Description": [
    {
      "lang": "en",
      "desc": "The positive NAA test result (e.g., PCR) must be older than 28 days."
    },
    {
      "lang": "de",
      "desc": "Der positive NAA-Test (z.B. PCR) muss mindestens 28 Tage zurückliegen."
    },
    {
      "lang": "fr",
      "desc": "Le test TAN positif (p. ex. PCR) doit dater d‘au moins 28 jours."
    },
    {
      "lang": "es",
      "desc": "Deben haber transcurrido como mínimo 28 días desde que una prueba de amplificación de ácidos nucleicos (por ejemplo, una PCR) diese positivo."
    },
    {
      "lang": "it",
      "desc": "Il NAAT positivo (ad es. test PRC) deve risalire minimo a 28 giorni fa."
    }
  ],
  "ValidFrom": "2021-07-03T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",
  "AffectedFields": [
    "r.0",
    "r.0.fr"
  ],
  "Logic": {
    "if": [
      {
        "var": "payload.r.0"
      },
      {
        "not-before": [
          {
            "plusTime": [
              {
                "var": "external.validationClock"
              },
              0,
              "day"
            ]
          },
          {
            "plusTime": [
              {
                "var": "payload.r.0.fr"
              },
              28,
              "day"
            ]
          }
        ]
      },
      true
    ]
  }
}
